MVC5WebApplication/Controllers/CountryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ServiceFunction;
using BusinessLayer.ServiceModel;
using EntityLayer.Model;
using Newtonsoft.Json;
using System;
using System.Linq;
using System.Web.Mvc;

namespace MVC5WebApplication.Controllers
{
    public class CountryController : Controller
    {
        CountryManager _countryManager = new CountryManager();
        CountryService.CountryInfoServiceSoapTypeClient client = new CountryService.CountryInfoServiceSoapTypeClient("CountryInfoServiceSoap");
        //CountryList list = new CountryList();

        public ActionResult Index()
        {
            var countrylist = client.ListOfCountryNamesByCode().ToList();
            var model = countrylist.Select(x => new ServiceCountryDetail { CountryName = x.sName, CountryISOCode = x.sISOCode }).ToList();
            ViewBag.countryNameList = countrylist.Select(x=> new SelectListItem
            {
                Text = x.sName,
                Value = x.sISOCode
            });
            return View();
        }
        [HttpPost]
        public ActionResult CountryDetails(string IsoCode)
        {
            try
            {
                var countrylist = client.ListOfCountryNamesByCode().ToList().Where(x => x.sISOCode == IsoCode).ToList();
                var cCurrency = client.CountryCurrency(IsoCode).sISOCode;
                var cCity = client.CapitalCity(IsoCode);
                var model = countrylist.Select(x => new ServiceCountryDetail { CountryName = x.sName, CountryISOCode = x.sISOCode, CapitalCity = cCity, CountryCurrency = cCurrency }).ToList();
                var json = JsonConvert.SerializeObject(model);
                return Json(json);
            }

            catch (Exception e)
            {

                return Json(new { result = e, message = e.Message });
            }

        }

        [HttpPost]
        public ActionResult Index(CountryInfo country)
        {
            country.Status = true;
            try
            {
                _countryManager.CountryAddBL(country);
                return Json(new { result = 1, message = "Başarılı." });
            }
            catch (Exception ex)
            {
                return Json(new { result = ex, message = ex.Message });
            }

        }
    }
}

MVC5WebApplication/Controllers/HomeController.cs
using System.Web.Mvc;

namespace MVC5WebApplication.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVC5WebApplication/Views/Country/Index.cshtml
@using EntityLayer.Model
@model CountryInfo
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="~/lib/jequery/dist/jequery.js"></script>

@using (Html.BeginForm("CountryDetails", "Country", FormMethod.Post, new { @class = "well form-horizontal" }))
{
    <table class="table" id="mvcTable">
        <thead>
            <tr>
                <th>Ülke</th>
                <th>Ülke Başkent</th>
                <th>Ülke Kısaltma</th>
                <th>Ülke Para Birimi</th>
            </tr>
        </thead>
        <tbody>
            
                <tr>
                    <td id="countryNameID">
                        @Html.DropDownListFor(Model => Model.CountryName, new SelectList(ViewBag.countryNameList, "Value", "Text"))
                    </td>
                    <td id="countryCodeID">@Html.DisplayFor(Model => Model.CountryCode)</td>
                    <td id="capitalCityID">@Html.DisplayFor(Model => Model.Capital)</td>
                    <td id="countryCurrencyID">@Html.DisplayFor(Model => Model.CurrencyUnit)</td>
                    <td>
                        <a href="#editEmployeeModal" class="btn btn-success" type="button" onclick="Kaydet()">Kaydet</a>
                    </td>
                </tr>
            

        </tbody>
    </table>

}

<script>
    $('select').on('change', function () {
        var value = $('#CountryName').select().val();
        $.ajax({
            url: "/Country/CountryDetails",
            data: { 'IsoCode': value },
            type: "post",
            success: function (response) {
                if (response != null) {
                    //Delete table row
                    //add New table row
                    var jsonData = jQuery.parseJSON(response);
                    console.log(jsonData);
                    console.log(response);
                    $('#countryCodeID').html(jsonData[0].CountryISOCode);
                    $('#capitalCityID').html(jsonData[0].CapitalCity);
                    $('#countryCurrencyID').html(jsonData[0].CountryCurrency);
                    $('#countryCodeID').val(jsonData[0].CountryISOCode);
                    $('#capitalCityID').val(jsonData[0].CapitalCity);
                    $('#countryCurrencyID').val(jsonData[0].CountryCurrency);
                    alert(response); 
                }
                else {
                    alert(response.message);
                }
            }
        })
    });



    function Kaydet() {
        $.ajax({
            url: "/Country/Index",
            data: {
                CountryName: $('#CountryName').select().val(),
                Capital: $('#capitalCityID').text(),
                CountryCode: $('#countryCodeID').text(),
                CurrencyUnit: $('#countryCurrencyID').text()
            },
            type: "post",
            cache: false,
            success: function (response) {
                if (response == true) {
                    alert(response.message);
                }
                else {
                    alert(response.message);
                }
            }
        })
    }</script>

MVC5WebApplication/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVC5WebApplication/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVC5WebApplication/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <a href="/Country"><h2> Ülkeler Tablosu</h2></a>
</div>

MVC5WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>